NAME = SineGenerator

TYPE = APP

APP_MIME_SIG = application/x-vnd-WakeUp

SRCS = SineGenerator.cpp TSliderView.cpp

RSRCS = SineGenerator.rsrc

## Include the Makefile-Engine
DEVEL_DIRECTORY := \
	$(shell findpaths -r "makefile_engine" B_FIND_PATH_DEVELOP_DIRECTORY)
include $(DEVEL_DIRECTORY)/etc/makefile-engine
